Correct ICD manipulation

diff --git a/nvvk b/nvvk
--- a/nvvk
+++ b/nvvk
@@ -64,6 +64,12 @@ function gpu_vendor() {
 
 # Get all ICD files
 function icd_files() {
+    IFS=":"
+    for file in ${VK_ICD_FILENAMES}; do
+        [ -f "${file}" ] && echo "${file}"
+    done
+    unset IFS
+
     for dir in ${_VK_ICD_PATH}; do
         if [ -d "${dir}" ]; then
             for file in "${dir}"/*.json; do
@@ -107,42 +113,48 @@ function nvidia_icd() {
     done
 }
 
+
+# Check if GPU running is AMD
+function is_amd() {
+    gpu_vendor | grep "AMD" 2>&1 > /dev/null
+    return $?
+}
+
+
+# Check if GPU running is NVIDI
+function is_nvidia() {
+    gpu_vendor | grep "NVIDIA" 2>&1 > /dev/null
+    return $?
+}
+
+
 # Check if user has glxinfo
 if ! command -v glxinfo &> /dev/null; then
     error "Unable to find glxinfo, please install it"
 fi
 
-if gpu_vendor | grep "AMD" 2>&1 > /dev/null; then
+# Get GPU and ICD
+if is_amd; then
 
     info "AMD card detected"
-
-    if [ ! -z "${AMD_VK_ICD_FILENAMES}" ]; then
-        export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 VK_ICD_FILENAMES="${AMD_VK_ICD_FILENAMES}"
-    elif [ -f "/usr/share/vulkan/icd.d/radeon_icd.i686.json" ] && [ -f "/usr/share/vulkan/icd.d/radeon_icd.x86_64.json" ]; then
-        info "Using amdvlk"
-        export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json"
-    elif [ -f "/usr/share/vulkan/icd.d/amd_icd32.json" ] && [ -f "/usr/share/vulkan/icd.d/amd_icd64.json" ]; then
-        info "Using RADV / Mesa Vulkan"
-        export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/amd_icd32.json:/usr/share/vulkan/icd.d/amd_icd64.json"
-    else
-        error "Unable to find amd ICD files. Please set \$AMD_VK_ICD_FILENAMES"
+    icd="$(amd_icd)"
+    if [ -z "${icd}" ]; then
+        error "Unable to find AMD ICD files. Make sure amdvlk or radeon-vulkan is installed"
     fi
 
-elif gpu_vendor | grep "NVIDIA" 2>&1 > /dev/null; then
+elif is_nvidia; then
 
     info "NVIDIA card detected"
-
-    if [ ! -z "${NV_VK_ICD_FILENAMES}" ]; then
-        export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 VK_ICD_FILENAMES="${NV_VK_ICD_FILENAMES}"
-    elif [ -f "/usr/share/vulkan/icd.d/nvidia_icd.json" ]; then
-        info "Using nvidia proprietary vulkan"
-        export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
-    else
-        error "Unable to find nvidia ICD file. Please set \$NV_VK_ICD_FILENAMES"
+    icd="$(nvidia_icd)"
+    if [ -z "${icd}" ]; then
+        error "Unable to find NVIDIA ICD files. Make sure nvidia proprietary drivers are installed"
     fi
 
 else
-    error "No GPU detected"
+    error "Unable to detect GPU"
 fi
 
+# Run command with correct ICD
+info "Using '${icd}'"
+export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1 VK_ICD_FILENAMES="${icd}"
 ${@}
